### ISSUE TITLE
Windows install failure

### ISSUE THREAD

**Issue by alecrabbit** [alecrabbit/php-console-spinner#10]
issue in [alecrabbit/php-reports](https://github.com/alecrabbit/php-reports/issues/8)

**Comment by alecrabbit** [comment]
new version released

**Comment by alecrabbit** [comment]
@honsa could you please inform me how new version is behaving?
what terminal are you using?
thanks

**Comment by honsa** [comment]
cmd.exe

![image](https://user-images.githubusercontent.com/526006/66562658-61181e80-eb5c-11e9-93e8-3e5dad959070.png)

PowerShell
![image](https://user-images.githubusercontent.com/526006/66562687-712ffe00-eb5c-11e9-8d63-ec9bf8406538.png)

PHPStorm Terminal
![image](https://user-images.githubusercontent.com/526006/66562850-c8ce6980-eb5c-11e9-87b9-fced2b058bb1.png)

**Comment by alecrabbit** [comment]
@honsa have you read note on windows use? 
this package uses ANSI control sequences, so your terminal should be compatible
I recommend minTTY which also is a part of git-bash
also you can try to install [ansicon](https://github.com/adoxa/ansicon)

**Comment by honsa** [comment]
Ok, thx

Under this conditions it works like expected:

![image](https://user-images.githubusercontent.com/526006/66563763-c967ff80-eb5e-11e9-88f6-c2987793c95b.png)

**Comment by alecrabbit** [comment]
Just to clarify, you are using cmd with ansicon installed right?
Thanks.

**Comment by honsa** [comment]
No, this is the PHP Storm terminal which has ansi support.

I corrected the post with the 3 screens, the 3. was PHP Storm Console not Terminal.

I have  now installed ansicon but have to wait for the next reboot to test it.

**Comment by alecrabbit** [comment]
@honsa oh, ok. 
Please keep me posted about ansicon.
Thanks.
