### ISSUE TITLE
Reason for PHP version constraint?

### ISSUE THREAD

**Issue by mortenscheel** [alecrabbit/php-console-spinner#11]
This is more a question than an issue.

I would like to use this package in a project that is (unfortunately) stuck on PHP 7.1.
The version constraint in `composer.json` requires >7.2, but I didn't notice any problems running the examples with PHP 7.1.
Is there a reason for this, or could the constraint be set to 7.1 in stead?

**Comment by alecrabbit** [comment]
sorry to hear that 
the reason was not to support package on 7.1
there were some issues with 7.1 at the moment and it already has been in "security fixes only" mode
idk what can be a solution here except updating your php installation or you can install this package manually
