### ISSUE TITLE
Raising eyebrowns on code quality

### ISSUE THREAD

**Issue by szepeviktor** [alecrabbit/php-console-spinner#8]
Hello @alecrabbit !

How could you write error-free code without static analysis??

![image](https://user-images.githubusercontent.com/952007/66437421-f961b680-ea29-11e9-8445-617f1f84bea8.png)

Up to now I haven't met a single error-free project not using @phpstan.

**Comment by szepeviktor** [comment]
I see: Psalm!

**Comment by alecrabbit** [comment]
Hi
I'm using them both phpstan and psalm, I have a tool for that in my workflow sh-php-dev-helper
